### ISSUE TITLE
Format der MAC

### ISSUE THREAD

**Issue by markuskobe** [mcdhrts/ioBroker.asuswrt#9]
Hi, in welchem Format muss die MAC-Adresse für die Konfiguration sein?
XXXXXXXXXXXX
XX:XX:XX:XX:XX:XX
XX-XX-XX-XX-XX-XX

Danke.

**Comment by mcdhrts** [comment]
Hi,

XX:XX:XX:XX:XX:XX ist das richtige Format.

Grüße

**Comment by markuskobe** [comment]
Danke, mit dem Laptop klappt es jetzt super...Leider wird das SmartPhone nicht gefunden...im Router sehe ich es..active bleibt immer auf false...last time active auf -1

**Comment by mcdhrts** [comment]
Kannst du bitte dich per Terminal / CMD einmal per SSH auf deinem Router anmelden und folgenden Befehl ausführen:

`PATH=$PATH:/bin:/usr/sbin:/sbin && ip neigh`

und dann schauen ob das Handy dort auftaucht und mit welchem Werten?

Anmelden am Router sollte mit:

`ssh ip-router -l anmeldename`

klappen. Beispiel: `ssh 10.0.0.1 -l admin`

Danke dir

**Comment by markuskobe** [comment]
Hi, hier der Auszug von "deinem" Befehl:

/tmp/home/root# PATH=$PATH:/bin:/usr/sbin:/sbin && ip neigh
169.254.39.27 dev br0 lladdr 54:a0:50:e5:59:cc REACHABLE
192.168.1.16 dev br0 lladdr d6:2c:78:06:c3:43 REACHABLE
192.168.1.132 dev br0 lladdr 3c:cd:93:97:9e:5f STALE
192.168.1.117 dev br0 lladdr 28:16:a8:5a:26:50 REACHABLE
192.168.1.254 dev br0 lladdr a0:e4:cb:3e:99:18 STALE


Laut Router (Typ RT-AC87U) via Web-Interface sind 29 Clients aktiv.

**Comment by mcdhrts** [comment]
Hm, in der IP Neighbour Tabelle von deinem Router stehen nur die 5 Adressen. 
Hast du bei dir Repeater im Einsatz oder verschiedene Netze am laufen?
Kannst du einmal prüfen was die ARP Tabelle ausgibt? Einfach `arp` ausführen wie vorhin. 
Beschreibung ARP: https://www.tldp.org/LDP/nag/node78.html
Beschreibung IP Neigh: http://man7.org/linux/man-pages/man8/ip-neighbour.8.html

**Comment by markuskobe** [comment]
Kann es daran liegen, dass es alles Löw-Energy Geräte sind? Sprich die nur Funken, wenn ein Bedarf ansteht?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mcdhrts** [comment]
Nein das sollte kein Problem sein. Ich habe bei mir über 30 Geräte über den Router sichtbar. Da sind iPhones, iPads, Android Handys, Laptops, WLAN Steckdosen usw. dabei und ich es sind alle in der Neighbour/Arp Tabelle sichtbar. Ich kann mir hier nur Repeater / Access Points vorstellen, weiß ich aber nicht ob das bei dir im Einsatz. Ich hab noch ein zweiten Asus Router als Mesh eingebunden und sehe auch die Geräte welche darüber eingeloggt sind. Wie ist denn das Netzwerk aufgebaut?

**Comment by markuskobe** [comment]
Hi, die ARP-Tabelle vom ASUS-Router hat nur drei Einträge....komisch...

Mein Netz lautet: 192.168.1.x
.254 -> DSL-Modem (liefert DHCP und DNS)
.100 -> Asus-Router (Als WLAN HotSpot)
.1-99 -> reserviert für statische Adressen, wie z.B. den ioBroker oder die CCU
.101-200 -> DHCP-Clients

Als einzige "Besonderheit" habe ich noch einen Powerline Adapter, der mir LAN im Keller zur Verfügung stellt, da hängt aber nur eine Kamera dran...kann also vernachlässigt werden...

Eine Idee wäre jetzt noch den DHCP-Service auf den ASUS zu verlagern...was meinst du?

**Comment by markuskobe** [comment]
Mist, die Idee mit DHCP auf dem Asus geht nicht...der läuft ja im AP-Mode...wenn ich ihn in den Router-Modus schalte, hätte ich zwei Router hintereinander...die blöde O2-Box kann nicht als "reines" DSL-Modem agieren...PPPoE Passthrough kann die auch nicht...abschalten kann ich die BOX auch nicht, da die meine Telefonie mit macht... wie kann ich dem ASUS beibringen, dass er seine ARP-Tabelle aktualisiert?

**Comment by markuskobe** [comment]
ok, wer lesen kann...mit "-s"

**Comment by markuskobe** [comment]
so, jetzt läuft es...bin wie von dir beschrieben per SSH auf den Router drauf, haben das Phone via ARP -s [Hostname] [MAC] in die ARP-Tabelle eingetragen...den Hostname habe ich mir über nslookup besorgt. Mir ist nur nicht klar, warum der Router die ARP-Tabelle nicht selbstständig vollständig erstellt...drei Einträge sind doch arg wenig.. Danke für deine schnelle Reaktion und hilfreichen Antworten.
